# Pytorch基础
## Numpy与Tensor
Tensor与Numpy相似，二者可共享内存，且相互间转换非常方便高效。二者最大的区别在于Numpy将ndarray放在CPU中加速运算，Tensor放在GPU中加速运算
### Tensor概述
1. torch.function 与 tensor.function等价，如torch.add(x, y)与x.add(y)
2. x.function返回一个新的Tensor，x.function_直接修改数据本身

In [2]:
import torch

x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = x.add(y)
print(z)
print(x)
x.add_(y)
print(x)

tensor([4, 6])
tensor([1, 2])
tensor([4, 6])


### 创建Tensor
可从列表或ndarray进行构建，也可根据指定形状构建

In [12]:
torch.Tensor([1, 2, 3, 4, 5, 6])    # 由列表构建
torch.Tensor(2, 3)    # 指定形状构建
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(t.size())    # 查看形状
print(t.shape)    # shape与size()等价
print(torch.Tensor(t.size()))

torch.Size([2, 3])
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


torch.Tensor与torch.tensor区别
1. torch.Tensor是torch.empty和torch.tensor的混合，但当传入数据时，torch.Tensor使用全局默认的dtype(FloatTensor)，torch.tensor从数据中推断数据类型
2. torch.tensor(1)返回固定值1，torch.Tensor(1)返回一个大小为1的随机初始化的张量

In [8]:
t1 = torch.Tensor(1)
t2 = torch.tensor(1)
print(f't1的值{t1}， t1的数据类型{t1.type()}')
print(f't2的值{t2}， t2的数据类型{t2.type()}')

t1的值tensor([-1.1395e-22])， t1的数据类型torch.FloatTensor
t2的值1， t2的数据类型torch.LongTensor


下面为根据一定规则自动生成 的一些Tensor

In [19]:
torch.eye(2, 2)    # 单位矩阵
torch.zeros(2, 3)
torch.linspace(1, 10, 4)
torch.rand(2, 3)
torch.randn(2, 3)    # 满足标准分布的随机数
torch.zeros_like(torch.rand(2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 修改Tensor形状

In [20]:
X = torch.randn(2, 3)

tensor([[ 0.6818,  0.8294,  0.8915],
        [-1.0143,  0.6292,  0.4269]])

查看形状

In [21]:
X.size()

torch.Size([2, 3])

查看维数

In [22]:
X.dim()

2

转换为3×2的矩阵

In [23]:
X.view(3, 2)

tensor([[ 0.6818,  0.8294],
        [ 0.8915, -1.0143],
        [ 0.6292,  0.4269]])

展平

In [24]:
X.view(-1)

tensor([ 0.6818,  0.8294,  0.8915, -1.0143,  0.6292,  0.4269])

添加一个维度

In [29]:
X.unsqueeze_(0)
X.size()

torch.Size([1, 2, 3])

计数

In [31]:
X.numel()

6

### 索引操作
